package com.vti;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Program2 {
	public static void main(String[] args) {

//	String url = "jdbc:mysql://127.0.0.1:3306/testing_system";
		String url = "jdbc:mysql://localhost:3306/railway87";
		String username = "root";
		String password = "root";

		Connection myConn;
		try {
			myConn = DriverManager.getConnection(url, username, password);
			if (myConn != null) {
				System.out.println("Đã được kết nối");
				Statement st = myConn.createStatement();
				String sql = "insert into 'users' (username, password)" + "values ('USER01', '123456')";
				PreparedStatement preparedStatement = myConn.prepareStatement(sql);
				int effectedRecordAmount = preparedStatement.executeUpdate();
				System.out.println("Số bản ghi đã được thêm vào" + effectedRecordAmount);

//				String sql = "update 'user'" + "Set 'username = USE01" + "where 'id' = 1";
//				PreparedStatement preparedStatement = myConn.prepareStatement(sql);
//				int effectedRecordAmount = preparedStatement.executeUpdate();
//				System.out.println("Số bản ghi đã được update" + effectedRecordAmount);
				myConn.close();

			} else {
				System.out.println("Không kết nối được");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();

		}

	}
}
